// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat.vue')['default']
    CorpEmoji: typeof import('./src/components/corpEmoji.vue')['default']
    Dod: typeof import('./src/components/dod.vue')['default']
    DodPGameMap: typeof import('./src/components/dodPGameMap.vue')['default']
    DodPGameMutator: typeof import('./src/components/dodPGameMutator.vue')['default']
    DodPGameTeam: typeof import('./src/components/dodPGameTeam.vue')['default']
    'DodPGameTeam copy': typeof import('./src/components/dodPGameTeam copy.vue')['default']
    DodPregame: typeof import('./src/components/dodPregame.vue')['default']
    FrdPanel: typeof import('./src/components/frdPanel.vue')['default']
    FrdSelectPanel: typeof import('./src/components/frdSelectPanel.vue')['default']
    Gem: typeof import('./src/components/gem.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    InputGrabber: typeof import('./src/components/inputGrabber.vue')['default']
    PBubbles: typeof import('./src/components/PBubbles.vue')['default']
    Pie: typeof import('./src/components/pie.vue')['default']
    Rglike: typeof import('./src/components/rglike.vue')['default']
    RglikeRecruit: typeof import('./src/components/rglikeRecruit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleComponent: typeof import('./src/components/sampleComponent.vue')['default']
    'SampleComponent copy': typeof import('./src/components/sampleComponent copy.vue')['default']
    SysEmail: typeof import('./src/components/sysEmail.vue')['default']
    UserCard: typeof import('./src/components/userCard.vue')['default']
    VisConfirmation: typeof import('./src/components/visConfirmation.vue')['default']
    VisLoading: typeof import('./src/components/visLoading.vue')['default']
    VisNotif: typeof import('./src/components/visNotif.vue')['default']
    VisUserInfo: typeof import('./src/components/visUserInfo.vue')['default']
  }
}

export {}
