// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat.vue')['default']
    Dod: typeof import('./src/components/dod.vue')['default']
    Gem: typeof import('./src/components/gem.vue')['default']
    InputGrabber: typeof import('./src/components/inputGrabber.vue')['default']
    PBubbles: typeof import('./src/components/PBubbles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleComponent: typeof import('./src/components/sampleComponent.vue')['default']
    'SampleComponent copy': typeof import('./src/components/sampleComponent copy.vue')['default']
  }
}

export {}
